version: '3.8'

services:
  db:
    container_name: db
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./docker-data/db:/var/lib/postgresql/data
    networks:
      - spizzichouse-network

  api:
    image: spizzichouse-api:${API_VERSION}
    ports:
      - "8080:3000"
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - spizzichouse-network
networks:
  spizzichouse-network: